# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('url', models.URLField(max_length=250)),
                ('uri', models.CharField(max_length=50)),
            ],
        ),
    ]
