# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='AlbumType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('spotify', 'spotify')], max_length=20)),
                ('type', models.CharField(choices=[('album', 'album'), ('single', 'single'), ('compilation', 'compilation')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('spotify', 'spotify')], max_length=20)),
                ('miliseconds', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('spotify', 'spotify')], max_length=20)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('spotify', 'spotify')], max_length=20)),
                ('type', models.CharField(choices=[('href', 'href'), ('id', 'id'), ('name', 'name'), ('uri', 'uri')], max_length=4)),
                ('identity', models.CharField(max_length=250)),
                ('cls', models.CharField(choices=[('str', 'str'), ('int', 'int')], default='str', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=36)),
                ('domain', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=1500)),
                ('version', models.CharField(max_length=20)),
                ('identifiers', models.ManyToManyField(to='app.Identifier')),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('spotify', 'spotify')], max_length=20)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=36)),
                ('acousticiness', models.FloatField()),
                ('durations', models.DurationField()),
                ('dancibility', models.FloatField()),
                ('energy', models.FloatField()),
                ('instrumentalness', models.FloatField()),
                ('key', models.PositiveSmallIntegerField()),
                ('liveness', models.FloatField()),
                ('loudness', models.FloatField()),
                ('mode', models.BooleanField()),
                ('popularity', models.PositiveSmallIntegerField()),
                ('signature', models.FloatField()),
                ('speechiness', models.FloatField()),
                ('tempo', models.FloatField()),
                ('valence', models.FloatField()),
                ('composers', models.ManyToManyField(to='app.Composer')),
                ('genres', models.ManyToManyField(to='app.Genre')),
                ('identifiers', models.ManyToManyField(to='app.Identifier')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=36)),
                ('identifiers', models.ManyToManyField(to='app.Identifier')),
                ('playlists', models.ManyToManyField(to='app.Playlist')),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(to='app.Track'),
        ),
        migrations.AddField(
            model_name='composer',
            name='genres',
            field=models.ManyToManyField(to='app.Genre'),
        ),
        migrations.AddField(
            model_name='composer',
            name='identifiers',
            field=models.ManyToManyField(to='app.Identifier'),
        ),
        migrations.AddField(
            model_name='album',
            name='composers',
            field=models.ManyToManyField(to='app.Composer'),
        ),
        migrations.AddField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(to='app.Genre'),
        ),
        migrations.AddField(
            model_name='album',
            name='identifiers',
            field=models.ManyToManyField(to='app.Identifier'),
        ),
        migrations.AddField(
            model_name='album',
            name='release_dates',
            field=models.ManyToManyField(to='app.ReleaseDate'),
        ),
        migrations.AddField(
            model_name='album',
            name='tracks',
            field=models.ManyToManyField(to='app.Track'),
        ),
        migrations.AddField(
            model_name='album',
            name='types',
            field=models.ManyToManyField(to='app.AlbumType'),
        ),
    ]
