# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 04:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify', models.BooleanField(default=False)),
                ('spotify_id', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('spotify_name', models.CharField(blank=True, max_length=200)),
                ('spotify_release', models.DateField(blank=True)),
                ('spotify_type', models.CharField(blank=True, choices=[('album', 'album'), ('single', 'single'), ('compilation', 'compilation')], max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify', models.BooleanField(default=False)),
                ('spotify_id', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('spotify_name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('spotify', 'spotify')], max_length=20)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('spotify', 'spotify')], max_length=7)),
                ('domain_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SpotifyProfile',
            fields=[
                ('id', models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False)),
                ('acousticiness', models.FloatField()),
                ('durations', models.DurationField()),
                ('dancibility', models.FloatField()),
                ('energy', models.FloatField()),
                ('instrumentalness', models.FloatField()),
                ('key', models.PositiveSmallIntegerField()),
                ('liveness', models.FloatField()),
                ('loudness', models.FloatField()),
                ('mode', models.BooleanField()),
                ('popularity', models.PositiveSmallIntegerField()),
                ('signature', models.FloatField()),
                ('speechiness', models.FloatField()),
                ('tempo', models.FloatField()),
                ('valence', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify', models.BooleanField(default=False)),
                ('spotify_durration', models.DurationField(blank=True)),
                ('spotify_id', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('spotify_name', models.CharField(blank=True, max_length=200)),
                ('composers', models.ManyToManyField(to='app.Composer')),
                ('genres', models.ManyToManyField(to='app.Genre')),
                ('spotify_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.SpotifyProfile')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify', models.BooleanField(default=False)),
                ('spotify_id', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('spotify_name', models.CharField(blank=True, max_length=200)),
                ('tracks', models.ManyToManyField(to='app.Track')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='playlist',
            unique_together=set([('domain', 'domain_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='genre',
            unique_together=set([('domain', 'name')]),
        ),
        migrations.AddField(
            model_name='composer',
            name='genres',
            field=models.ManyToManyField(to='app.Genre'),
        ),
        migrations.AddField(
            model_name='album',
            name='composers',
            field=models.ManyToManyField(to='app.Composer'),
        ),
        migrations.AddField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(to='app.Genre'),
        ),
    ]
