# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160914_0426'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Album',
            new_name='Collection',
        ),
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(to='app.Track'),
        ),
        migrations.AddField(
            model_name='track',
            name='collections',
            field=models.ManyToManyField(to='app.Collection'),
        ),
    ]
