# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160907_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Base')),
                ('playlists', models.ManyToManyField(to='app.Playlist')),
            ],
            bases=('app.base',),
        ),
    ]
