# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160914_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='link',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
