# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_playlist_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='link',
        ),
    ]
