# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20160916_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='summary',
        ),
    ]
