# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 02:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_playlist_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='spotify',
        ),
        migrations.RemoveField(
            model_name='composer',
            name='spotify',
        ),
        migrations.RemoveField(
            model_name='track',
            name='spotify',
        ),
        migrations.RemoveField(
            model_name='user',
            name='spotify',
        ),
    ]
