# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 03:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20160921_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='genres',
        ),
    ]
