# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_collection_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='genres',
            field=models.ManyToManyField(to='app.Genre'),
        ),
    ]
