# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 00:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20160921_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='spotify_durration',
            new_name='spotify_duration',
        ),
    ]
