# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20160922_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='spotify_profile',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.SpotifyProfile'),
        ),
    ]
