# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20160922_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='publisher',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
