# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-30 21:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20160928_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composer',
            name='spotify_created',
        ),
        migrations.RemoveField(
            model_name='composer',
            name='spotify_updated',
        ),
    ]
