# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-01 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20161001_0331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifyprofile',
            old_name='dancibility',
            new_name='danceability',
        ),
    ]
