# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-01 22:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20161001_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifyprofile',
            old_name='acousticiness',
            new_name='acousticness',
        ),
    ]
