# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20161001_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyprofile',
            name='signature',
            field=models.FloatField(blank=True),
        ),
    ]
