# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20161004_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='upc',
            field=models.IntegerField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='isrc',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
