# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20161004_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='upc',
            field=models.BigIntegerField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='isrc',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
